# Generated by Django 5.1.6 on 2025-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Имя домена')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки домена')),
            ],
        ),
    ]
